env:
  browser: true
  es2022: true
extends: eslint:recommended
parserOptions:
  sourceType: module
rules:
    eqeqeq:
      - warn
      - always
    indent:
      - error
      - 4
      - ignoredNodes:
        - Program > BlockStatement
        - Program > ExpressionStatement > CallExpression > ArrowFunctionExpression > BlockStatement
        - Program > ExpressionStatement > CallExpression > FunctionExpression > BlockStatement
        - Program > IfStatement > BlockStatement
        - Program > VariableDeclaration > VariableDeclarator > CallExpression > ArrowFunctionExpression > BlockStatement
        - CallExpression > MemberExpression
        - ArrayExpression > *
        - ObjectExpression > *
    no-control-regex: off
    no-empty: off
    sort-imports: warn
    strict: warn
globals:
    browser: readonly
    chrome: readonly
    vAPI: readonly
